# Generated by Django 5.1.1 on 2025-04-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_business",
            field=models.BooleanField(default=False),
        ),
    ]
