# Generated by Django 5.1.1 on 2025-05-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_usermodel_is_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="bio",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="birthday",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
