# Generated by Django 5.1.1 on 2025-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_usermodel_bio_usermodel_birthday_usermodel_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="address",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
