# Generated by Django 5.1.1 on 2025-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="business",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="post_videos"),
        ),
        migrations.DeleteModel(
            name="PostMediaModel",
        ),
    ]
