# Generated by Django 5.1.1 on 2025-04-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessmodel",
            name="background_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="business_backgrounds/"
            ),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="business_profiles/"
            ),
        ),
    ]
