# Generated by Django 5.1.1 on 2025-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_businessmodel_background_profile_businessmodel_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
