# Generated by Django 5.1.1 on 2025-04-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("user", "0003_businessmodel_created_at_businessmodel_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessmodel",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.countrymodel",
            ),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="businessmodel",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
