# Generated by Django 5.1.1 on 2025-05-01 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_commentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="user.commentmodel",
            ),
        ),
    ]
