# Generated by Django 5.1.1 on 2025-05-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_commentmodel_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentmodel",
            old_name="user",
            new_name="author",
        ),
    ]
