# Generated by Django 5.1.1 on 2025-05-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_rename_user_commentmodel_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentmodel",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="commentmodel",
            name="parent",
        ),
    ]
