# Generated by Django 5.1.1 on 2025-05-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_rename_author_commentmodel_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentmodel",
            old_name="user",
            new_name="author",
        ),
    ]
